Bugfix/tags page
Ventan00/quanda pull request #113
Opened 2021-09-29 19:36 UTC by Patrykoss

2021-09-30 00:02 UTC, xlegodroit requested changes

2021-09-30 00:02 UTC, xlegodroit commented on Client/Pages/Tags/SubTags.razor.cs
> +        public RightMenuStateService RightMenuStateService { get; set; }
Should be removed

2021-09-30 00:02 UTC, xlegodroit commented on Client/Pages/Tags/Tags.razor.cs
> +        public RightMenuStateService RightMenuStateService { get; set; }
Should be removed

2021-09-30 08:16 UTC, xlegodroit approved these changes

2021-10-02 18:16 UTC, Ventan00 approved these changes
OK

2021-10-03 22:28 UTC, merged