Profile picture of logged user and bugfixes
Ventan00/quanda pull request #20
Opened 2021-08-02 18:57 UTC by Ventan00

* Added profile picture of logged user
* Added commented mock user for testing purposes
* Fixed Mozilla bug for logo scaling
* Removed element causing white field under footer

2021-08-02 21:07 UTC, Patrykoss commented on Client/Shared/TopBarComponent.razor
> +    ///     Zmienna przechowująca watar
Literówka sumary Avatar

2021-08-02 21:12 UTC, Patrykoss requested changes
Small typo

2021-08-02 21:26 UTC, xlegodroit reviewed
Everything is ok, except typo already mentioned above

2021-08-03 07:51 UTC, Patrykoss approved these changes
Ok

2021-08-03 12:44 UTC, xlegodroit approved these changes

2021-08-03 16:47 UTC, merged